import time
import os

Color34 = "\u001b[34m"
Color37 = "\u001b[37m"

def icecream1():
    print("         _.-.")
    print("       ,'/ //\ ")
    print("      /// // /)")
    print("     /// // //|")
    print("    /// // ///")
    print("   /// // ///")
    print("  (`: // ///")
    print("   `;`: ///")
    print("   / /:`:/")
    print("  / /  `'") 
    print(" / /")
    print("(_/")
    print("\u001b[34m -------------------------------------------- \u001b[37m")

def icecream2():
    print("              _.-.")
    print("            ,'/ //\ ")
    print("           /// // /)")
    print("          /// // //|")
    print("         /// // ///")
    print("        /// // ///")
    print("       (`: // ///")
    print("        `;`: ///")
    print("        / /:`:/")
    print("       / /  `'") 
    print("      / /")
    print("     (_/")
    print("\u001b[34m -------------------------------------------- \u001b[37m")

def icecream3():
    print("                   _.-.")
    print("                 ,'/ //\ ")
    print("                /// // /)")
    print("               /// // //|")
    print("              /// // ///")
    print("             /// // ///")
    print("            (`: // ///")
    print("             `;`: ///")
    print("             / /:`:/")
    print("            / /  `'") 
    print("           / /")
    print("          (_/")
    print("\u001b[34m -------------------------------------------- \u001b[37m")

def icecream4():
    print("                        _.-.")
    print("                      ,'/ //\ ")
    print("                     /// // /)")
    print("                    /// // //|")
    print("                   /// // ///")
    print("                  /// // ///")
    print("                 (`: // ///")
    print("                  `;`: ///")
    print("                  / /:`:/")
    print("                 / /  `'") 
    print("                / /")
    print("               (_/")
    print("\u001b[34m -------------------------------------------- \u001b[37m")

def icecream5():
    print("                             _.-.")
    print("                           ,'/ //\ ")
    print("                          /// // /)")
    print("                         /// // //|")
    print("                        /// // ///")
    print("                       /// // ///")
    print("                      (`: // ///")
    print("                       `;`: ///")
    print("                       / /:`:/")
    print("                      / /  `'") 
    print("                     / /")
    print("                    (_/")
    print("\u001b[34m -------------------------------------------- \u001b[37m")

def icecream6():
    print("                                  _.-.")
    print("                                ,'/ //\ ")
    print("                               /// // /)")
    print("                              /// // //|")
    print("                             /// // ///")
    print("                            /// // ///")
    print("                           (`: // ///")
    print("                            `;`: ///")
    print("                            / /:`:/")
    print("                           / /  `'") 
    print("                          / /")
    print("                         (_/")
    print("\u001b[34m -------------------------------------------- \u001b[37m")


os.system("clear")
time.sleep(.1)
icecream1()
time.sleep(.5)
os.system("clear")
icecream2()
time.sleep(.5)
os.system("clear")
icecream3()
time.sleep(.5)
os.system("clear")
icecream4()
time.sleep(.5)
os.system("clear")
icecream5()
time.sleep(.5)
os.system("clear")
icecream6()
time.sleep(.5)
os.system("clear")
